#!/usr/bin/python3
from math import sqrt, sin, cos, tan, atan2, ceil, radians, degrees, asin, acos, log, pi, e, atan, modf, floor, trunc, fabs
import datetime
import sys
import re
import ephem
from almanac import haversine, ahaversine, compute_hczn, height_of_eye, refraction

# TODO: use the more recent skyfield library?
# YES we need to do this because ephem generates data that doesn't
# match the almanac.
#import skyfield

def parse_dms(x):
	if g := re.match(r"([-+]?\d+)([NSEW])(\d+[.]?\d*)?", x):
		print(g[3])
		degs = int(g[1])
		mins = float(g[3])
		sign = -1 if g[2] == "S" or g[2] == "W" else +1
		return (degs + mins / 60) * sign 
	return float(x)

# Amsterdam 52°21'48.8"N 4°54'07.9"E
# East is positive
if len(sys.argv) > 2:
	lat = parse_dms(sys.argv[1])
	lon = parse_dms(sys.argv[2])
else:
	lat = +(52 + 21/60 + 48.8/3600)
	lon = +(4 + 54/60 + 7.9/3600)
height_eye = 4.5
dr_lat = trunc(lat)
dr_lon = trunc(lon)

#lat = 24.581199
#lon = -20.42402
#lon = +15
#lat = +(8 + 4/60)

def fmt_deg(x, zero_deg=False):
	return "%+ 8.3f" % (x)
	return "%+ 8.3f" % (degrees(x))
	x = degrees(x)
	if x < 0:
		neg = '-'
		x = -x
	else:
		neg = ''

	(m,d) = modf(x)
	m *= 60

	if d == 0 and not zero_deg:
		return "%s%.1f'" % (neg,m)
	return "%+4d°%04.1f'" % (-d if neg else d,m)



# The ephem library always wants UTC
def ephem_date(when):
	date = when.isoformat()
	date = re.sub(r"T"," ", date)
	date = re.sub(r"-","/", date)
	return date


# Given a timestamp in UTC, compute the position of the sun
# note that the GHA is positive going west, while longitude
# is positive going east!
def sun_position(when):
	sun = ephem.Sun(ephem_date(when))
	gha = degrees(sun.ha)
	if gha > 180:
		gha -= 360
	return (degrees(sun.dec),gha)
	

# double check with the epehm library
def compute_hc_ephem(lat,lon,when):
	pos = ephem.Observer()
	pos.lat = radians(lat)
	pos.lon = radians(lon)
	pos.elevation = 0
	pos.pressure = 0
	pos.date = ephem_date(when)
	sun = ephem.Sun(pos)
	return (fmt_deg(degrees(sun.alt)), fmt_deg(degrees(sun.az)))

def hczn_table(lat, dec, lha):
	# round all of the values in the correct directions
	lat = floor(lat)
	dec = trunc(dec)
	lha = trunc(lha)
	#print(f"table {lat=} {dec=} {lha=}", file=sys.stderr)
	(hc1,zn) = compute_hczn(lat,dec,lha)

	# compute the d value
	if dec < 0:
		dec -= 1
	else:
		dec += 1
	(hc2,_) = compute_hczn(lat,dec,lha)
	return (hc1,zn,floor((hc2 - hc1) * 100))
	

# Given a lat/lon and time, compute the height of the sun at that position
def compute_hc(lat, lon, when):
	(sun_dec,sun_gha) = sun_position(when)
	# note that longitude is increasing going east,
	# but the sun hour angle is increasing going west.
	# so the angle between them is the sum, not the difference
	lha = lon - (-sun_gha)
	(hc,zn) = compute_hczn(lat, sun_dec, lha)

	return (hc,zn,sun_dec,sun_gha,lha)


tz = datetime.timezone(datetime.timedelta(hours=1))
day = datetime.datetime(2026, 4, 29, 0, 0)
(_,_,noon_decl,noon_gha,_) = compute_hc(lat,lon, day + datetime.timedelta(hours=12))
(_,_,noon2_decl,_,_) = compute_hc(lat,lon, day + datetime.timedelta(hours=12+24))
decl_d = 60 * (noon2_decl - noon_decl) / 24

print("Date", day)
print("Location", fmt_deg(lat), fmt_deg(lon))
print("DR  ", fmt_deg(dr_lat), fmt_deg(dr_lon))
print("EOT ", fmt_deg(noon_gha), "DECL", fmt_deg(noon_decl), "%.2f" % (decl_d))

#print(compute_hczn(52,-21, -26))
#print(compute_hczn(52,-21, +44))


#      00:00 27.68 26.96 26.84  -7.1  56.7 -179.4 -309.4 -309.7 +14.401 47.25 50.89
print("UTC   Hs    Ho    Hc     err   Zn   GHA    DR_LHA LHA    Decl    T1    T2")
for h in range(0,23):
	for m in [0,15,30,45]:
		d = day + datetime.timedelta(hours=h, minutes=m)

		# the exact height that you should see
		(ho,zn,decl,gha,lha) = compute_hc(lat,lon, d)
		if ho < 0:
			continue


		# hs is the height before sextant corrections
		# it will be higher than the actual height
		dip = height_of_eye(ho)
		refr = refraction(ho)
		hs = ho + (dip + refr)/60

		#(hc2,zn2) = compute_hc_ephem(lat,lon, d)

		# compute the DR height based on the assumed latitude
		# and longitude.
		# use the DR position to compute the LHA,
		# since the actual lon is unknown when taking the sights
		dr_lha = dr_lon - (-gha)

		(hc,zn_dr) = compute_hczn(dr_lat, decl, dr_lha)
		d = (hc - ho) * 60

		transfer = ahaversine(haversine(dr_lha) * cos(radians(dr_lat)) * cos(radians(decl)))
		transfer2 = ahaversine(haversine(90-decl) - haversine(dr_lat - hc))

		print("%02d:%02d" % (h,m),
			"%5.2f %5.2f" % (hs, ho),
			"%5.2f %+5.1f %5.1f" % (hc, d, zn),
			"%+6.1f %+6.1f %+6.1f %+6.3f" % (gha, dr_lha, lha, decl),
			#"%5.2f %+6.2f" % (hc3, hc - hc3),
			#fmt_deg(gha),
			#fmt_deg(dr_lha),
			#fmt_deg(lha),
			#fmt_deg(decl),
			"%5.2f %5.2f" % (transfer, transfer2),
		)
